<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.qoop</groupId>
        <artifactId>qoop-ejb-global</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>qoop-ejb-global-core</artifactId>
    <packaging>jar</packaging>

    <name>qoop-ejb-global-core</name>

    <dependencies>
        <!-- Internal Dependencies -->
        <dependency>
            <groupId>ir.tamin.framework.logging</groupId>
            <artifactId>logging-api</artifactId>
        </dependency>
    </dependencies>
</project>
