<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.qoop</groupId>
        <artifactId>qoop-ejb-cacheable</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>qoop-ejb-cacheable-core</artifactId>

    <dependencies>
        <!-- Nonbinding + Inject + ApplicationScoped -->
        <dependency>
            <groupId>javax.enterprise</groupId>
            <artifactId>cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- InterceptorBinding + Interceptor + AroundInvoke -->
        <dependency>
            <groupId>javax.interceptor</groupId>
            <artifactId>javax.interceptor-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>

        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
        </dependency>

        <!-- PostConstruct + PreDestroy + Priority -->
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
        </dependency>

        <dependency>
            <groupId>javax.ejb</groupId>
            <artifactId>javax.ejb-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>

        <!-- Internal Dependencies -->
        <dependency>
            <groupId>ir.tamin.framework.logging</groupId>
            <artifactId>logging-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-ejb-global-core</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-ejb-cacheable-api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>qoop-ejb-util-core</artifactId>
        </dependency>
    </dependencies>
</project>
